
using InputActions.Data.Interface;
using InputCapturePlayUi.Data;
using InputCapturePlayUi.InputActionsApi;
using InputCapturePlayUi.InputFileIo;
using InputCapturePlayUi.InputFileIo.Interface;
using System;
using System.Collections.Generic;
using System.Windows.Forms;

namespace InputCapturePlayUi
{
    public partial class Form1 : Form
    {

        private IFormsInputActionFacade _dataGridInputAction;
        private IFramesToMsConverter _framesToMsConverter;
        private IInputFileWriter _inputFileWriter;
        private IInputFileReader _inputFileReader;

        public Form1()
        {
            InitializeComponent();
            InitializeDataGridColumns(); 
            _dataGridInputAction = new DataGridInputAction();
            _framesToMsConverter = new FramesToMsConverter60fps();
            _inputFileWriter = new InputFileWriter();
            _inputFileReader = new InputFileReader(); 
        }

        private void InitializeDataGridColumns()
        {
            this.InputType.ValueType = typeof(FormsInputTypes);
            this.InputType.CellTemplate.ValueType = typeof(FormsInputTypes);
            this.InputType.DataSource = new List<FormsInputTypes>() {
                FormsInputTypes.Charge,
                FormsInputTypes.HoldDown,
                FormsInputTypes.Press,
                FormsInputTypes.Release };
        }

        private void Form1_Load(object sender, EventArgs e)
        {

        }

        /// <summary>
        /// Play button
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void button1_Click(object sender, EventArgs e)
        {
            try
            {
                _dataGridInputAction.LoadInput(this.dataGridView1, _framesToMsConverter);
                _dataGridInputAction.PlayInput();
            }
            catch (System.Exception ex)
            {
                MessageBox.Show("There was an error with attempting to process and play back the inputs. Please make sure Snes9x is running, and the entered values are as follows: \n One or more rows are completely filled out \n Key is a string value \n Input Type is from the drop down \n Delay is a whole number \n Charge Duration is a whole number");
            }
            
        }

        private void saveInputFileToolStripMenuItem_Click(object sender, EventArgs e)
        {

            try {

                _dataGridInputAction.LoadInput(this.dataGridView1, _framesToMsConverter);
                
            }
            catch (Exception ex)
            {
                MessageBox.Show("There was an error with attempting to read the inputs. Please make sure the entered values are as follows: \n One or more rows are completely filled out \n Key is a string value \n Input Type is from the drop down \n Delay is a whole number \n Charge Duration is a whole number ");
            }

            try
            {
                IInputQueue inputQueue = _dataGridInputAction.LoadedInputQueue;
                if (saveFileDialog1.ShowDialog() == DialogResult.OK)
                {
                    string fileName = saveFileDialog1.FileName;
                    _inputFileWriter.WriteInputQueueToFile(inputQueue, fileName);
                }
            }
            catch(Exception ex)
            {
                MessageBox.Show("There was an error attempting to save the file."); 
            }


        }

        private void saveToolStripMenuItem_Click(object sender, EventArgs e)
        {
            try
            {
                if (openFileDialog1.ShowDialog() == DialogResult.OK)
                {
                    string fileName = openFileDialog1.FileName;
                    IInputQueue inputQueue = _inputFileReader.CreateInputQueueFromFile(fileName);
                    this.dataGridView1.Rows.Clear(); 
                    _dataGridInputAction.LoadInputFromQueueToGrid(inputQueue, this.dataGridView1, _framesToMsConverter);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("There was an error attempting to load the file. Please use a file that was originally generated by this application."); 
            }
            
            
        }
    }
}
